spring:
  application:
    name: distributedlock
distributedlock:
  node:
    name: ${NODE_NAME:node1}
    url: ${NODE_URL:http://localhost:8080}
    electionTimeout: 6000
    gossipInterval: 3000
  raft:
    seeds: ${RAFT_SEEDS:http://localhost:8081,http://localhost:8082}
  expirationTime: 120
server:
  port: ${SERVER_PORT:8080}
