apiVersion: 1

datasources:
  - name: Loki
    uid: loki-distributedlock
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      maxLines: 5000
      derivedFields:
        - name: TraceID
          matcherRegex: '"traceId":"([^"]+)"'
          url: ""
          datasourceUid: ""
    editable: false

